<?php
require_once '../../core/session.php';
require_once '../../core/functions.php';

// Security: Only Super Admin can access this report
if ($_SESSION['role'] !== 'super_admin') {
    die("Access Denied");
}

// 0. Fetch System Settings
$settings = [];
$stmt = $pdo->query("SELECT * FROM system_settings");
while ($row = $stmt->fetch()) {
    $settings[$row['setting_key']] = $row['setting_value'];
}

// Fetch Data for Report
$systemName = $settings['system_name'] ?? 'Complaint Management System';

// 1. Basic Stats
$totalComplaints = $pdo->query("SELECT COUNT(*) FROM complaints")->fetchColumn();
$pendingCount = $pdo->query("SELECT COUNT(*) FROM complaints WHERE status = 'Pending'")->fetchColumn();
$resolvedCount = $pdo->query("SELECT COUNT(*) FROM complaints WHERE status = 'Resolved'")->fetchColumn();
$inProcessCount = $pdo->query("SELECT COUNT(*) FROM complaints WHERE status = 'In-Process'")->fetchColumn();
$closedCount = $pdo->query("SELECT COUNT(*) FROM complaints WHERE status = 'Closed'")->fetchColumn();
$avgRating = $pdo->query("SELECT ROUND(AVG(rating), 1) FROM complaints WHERE rating IS NOT NULL")->fetchColumn() ?: 0;

// 2. Department Statistics
$deptStats = $pdo->query("SELECT d.dept_name, COUNT(c.id) as total, 
                          SUM(CASE WHEN c.status = 'Resolved' THEN 1 ELSE 0 END) as resolved
                          FROM departments d 
                          LEFT JOIN categories cat ON d.id = cat.dept_id 
                          LEFT JOIN complaints c ON cat.id = c.category_id 
                          GROUP BY d.id")->fetchAll();

// 3. Category Stats
$catStats = $pdo->query("SELECT cat.category_name, COUNT(c.id) as count 
                         FROM categories cat 
                         LEFT JOIN complaints c ON cat.id = c.category_id 
                         GROUP BY cat.id 
                         ORDER BY count DESC")->fetchAll();

// 4. Detailed Complaint List (Last 50)
$complaintsDetail = $pdo->query("SELECT c.id, c.subject, c.status, c.priority, c.created_at, u.name as user_name, cat.category_name
                                 FROM complaints c
                                 JOIN users u ON c.user_id = u.id
                                 JOIN categories cat ON c.category_id = cat.id
                                 ORDER BY c.created_at DESC
                                 LIMIT 50")->fetchAll();

?>
<!DOCTYPE html>
<html lang="en text-dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Executive Complaint Report - <?= date('Y-m-d') ?></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.min.css">
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: 14px; }
        .report-header { border-bottom: 3px solid #000; padding-bottom: 20px; margin-bottom: 30px; }
        .stat-box { border: 1px solid #dee2e6; padding: 15px; border-radius: 8px; text-align: center; }
        .stat-box h3 { margin-bottom: 0; font-weight: bold; }
        .table-custom { font-size: 12px; }
        @media print {
            .no-print { display: none !important; }
            body { padding: 20px; }
            .bg-light { background-color: #f8f9fa !important; -webkit-print-color-adjust: exact; }
            .badge { border: 1px solid #000; }
        }
    </style>
</head>
<body class="bg-light">

    <div class="container my-5 bg-white p-5 shadow-sm rounded">
        
        <!-- Controls -->
        <div class="no-print text-end mb-4">
            <button onclick="window.print()" class="btn btn-primary btn-lg rounded-pill shadow">
                <i class="bi bi-printer-fill me-2"></i> Print or Save as PDF
            </button>
            <button onclick="window.close()" class="btn btn-outline-secondary btn-lg rounded-pill ms-2">
                Close
            </button>
        </div>

        <div class="report-header d-flex justify-content-between align-items-center">
            <div class="d-flex align-items-center">
                <?php if(!empty($settings['system_logo'])): ?>
                    <img src="<?= $settings['system_logo'] ?>" height="60" class="me-3" alt="Logo">
                <?php endif; ?>
                <div>
                    <h1 class="fw-bold mb-0"><?= htmlspecialchars($systemName) ?></h1>
                    <p class="text-muted mb-0">Official Executive Complaint Report</p>
                </div>
            </div>
            <div class="text-end">
                <p class="mb-0 fw-bold">Date Generated: <?= date('F j, Y') ?></p>
                <p class="mb-0 text-muted">Generated by: <?= htmlspecialchars($_SESSION['name']) ?></p>
            </div>
        </div>

        <!-- 1. Executive Summary -->
        <h4 class="mb-3 border-start border-primary border-5 ps-3 fw-bold">Executive Summary</h4>
        <div class="row g-3 mb-5">
            <div class="col">
                <div class="stat-box bg-white h-100">
                    <p class="text-muted small text-uppercase mb-1">Total</p>
                    <h3 class="text-dark"><?= $totalComplaints ?></h3>
                </div>
            </div>
            <div class="col">
                <div class="stat-box bg-white h-100">
                    <p class="text-muted small text-uppercase mb-1">Pending</p>
                    <h3 class="text-warning"><?= $pendingCount ?></h3>
                </div>
            </div>
            <div class="col">
                <div class="stat-box bg-white h-100">
                    <p class="text-muted small text-uppercase mb-1">In-Process</p>
                    <h3 class="text-info"><?= $inProcessCount ?></h3>
                </div>
            </div>
            <div class="col">
                <div class="stat-box bg-white h-100">
                    <p class="text-muted small text-uppercase mb-1">Resolved</p>
                    <h3 class="text-success"><?= $resolvedCount ?></h3>
                </div>
            </div>
            <div class="col">
                <div class="stat-box bg-white h-100">
                    <p class="text-muted small text-uppercase mb-1">Satisfaction</p>
                    <h3 class="text-primary"><?= $avgRating ?>/5</h3>
                </div>
            </div>
        </div>

        <!-- 2. Performance Breakdown -->
        <div class="row mb-5">
            <div class="col-md-6">
                <h5 class="fw-bold mb-3"><i class="bi bi-building me-2"></i>Departmental Performance</h5>
                <table class="table table-bordered table-custom shadow-sm bg-white">
                    <thead class="table-dark">
                        <tr>
                            <th>Department</th>
                            <th class="text-center">Total</th>
                            <th class="text-center">Resolved</th>
                            <th class="text-center">Success Rate</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($deptStats as $d): 
                            $rate = $d['total'] > 0 ? round(($d['resolved'] / $d['total']) * 100) : 0;
                        ?>
                            <tr>
                                <td><?= htmlspecialchars($d['dept_name']) ?></td>
                                <td class="text-center"><?= $d['total'] ?></td>
                                <td class="text-center text-success fw-bold"><?= $d['resolved'] ?></td>
                                <td class="text-center">
                                    <div class="fw-bold <?= $rate > 70 ? 'text-success' : ($rate > 40 ? 'text-warning' : 'text-danger') ?>">
                                        <?= $rate ?>%
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="col-md-6">
                <h5 class="fw-bold mb-3"><i class="bi bi-tags me-2"></i>Issue Distribution</h5>
                <table class="table table-bordered table-custom shadow-sm bg-white">
                    <thead class="table-info">
                        <tr>
                            <th>Category Name</th>
                            <th class="text-center">Complaint Count</th>
                            <th class="text-center">Share</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($catStats as $c): 
                            $share = $totalComplaints > 0 ? round(($c['count'] / $totalComplaints) * 100) : 0;
                        ?>
                            <tr>
                                <td><?= htmlspecialchars($c['category_name']) ?></td>
                                <td class="text-center"><?= $c['count'] ?></td>
                                <td class="text-center text-muted"><?= $share ?>%</td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>

        <!-- 3. Detailed Records -->
        <h5 class="fw-bold mb-3"><i class="bi bi-table me-2"></i>Comprehensive Logs (Last 50 Records)</h5>
        <table class="table table-striped table-bordered table-custom shadow-sm bg-white">
            <thead class="table-secondary">
                <tr>
                    <th>ID</th>
                    <th>Date</th>
                    <th>User</th>
                    <th>Category</th>
                    <th>Subject</th>
                    <th class="text-center">Priority</th>
                    <th class="text-center">Status</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($complaintsDetail as $c): ?>
                    <tr>
                        <td class="fw-bold">#<?= $c['id'] ?></td>
                        <td><?= date('d M, Y', strtotime($c['created_at'])) ?></td>
                        <td><?= htmlspecialchars($c['user_name']) ?></td>
                        <td><?= htmlspecialchars($c['category_name']) ?></td>
                        <td style="max-width: 200px;" class="text-truncate"><?= htmlspecialchars($c['subject']) ?></td>
                        <td class="text-center">
                            <span class="text-uppercase small fw-bold <?= $c['priority'] === 'High' ? 'text-danger' : ($c['priority'] === 'Medium' ? 'text-warning' : 'text-success') ?>">
                                <?= $c['priority'] ?>
                            </span>
                        </td>
                        <td class="text-center">
                            <span class="badge rounded-pill bg-light text-dark border border-secondary px-3">
                                <?= $c['status'] ?>
                            </span>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <!-- Footer -->
        <div class="mt-5 pt-4 border-top text-center text-muted small">
            <p>This report is generated automatically by the <?= htmlspecialchars($systemName) ?>. 
               All data is confidential and intended for organizational use only.</p>
            <p>&copy; <?= date('Y') ?> <?= htmlspecialchars($systemName) ?>. All rights reserved.</p>
        </div>

    </div>

    <!-- Automatically open print dialog -->
    <script>
        window.onload = function() {
            // Optional: Uncomment the line below to auto-open the print dialog
            // window.print();
        }
    </script>
</body>
</html>
